export const cartItemStyles = [
  {
    title: "Reason one",
    titleStyles: [
      "text-center",
      "rounded-md",
      "w-40",
      "py-1.5",
      "px-6",
      "bg-cardBorderBlue",
      "relative",
      "top-4",
    ].join(" "),
    details: ["reason blablabla", "reason blablabl", "reason blablabla"],
    containerStyles: ["w-full", "rounded-lg", "bg-cardBorderBlue", "p-1"].join(" "),
    gradient: ["bg-cardBorderBlue"],
  },
  {
    title: "Reason two",
    titleStyles: [
      "text-center",
      "rounded-md",
      "w-40",
      "py-1.5",
      "px-6",
      "bg-btn",
      "relative",
      "top-4",
    ].join(" "),
    details: ["reason blablabla", "reason blablabl", "reasonblablabla"],
    containerStyles: ["w-full", "rounded-lg", "bg-btn", "p-1"].join(" "),
    gradient: ["bg-btn"],
  },
  {
    title: "Reason three",
    titleStyles: [
      "text-center",
      "rounded-md",
      "w-40",
      "py-1.5",
      "px-6",
      "bg-cardBorder",
      "relative",
      "top-4",
    ].join(" "),
    details: ["reason blablabla", "reason blablabl", "reasonblablabla"],
    containerStyles: ["w-full", "rounded-lg", "bg-cardBorder", "p-1"].join(" "),
    gradient: ["bg-cardBorder"],
  },
];
